#CONFIG_ZTEST=y
#CONFIG_TEST_USERSPACE=y
CONFIG_CPP=y

CONFIG_TIMING_FUNCTIONS=y
CONFIG_CBPRINTF_FP_SUPPORT=y
#CONFIG_ASSERT=y
CONFIG_PWM=y
CONFIG_GPIO=y

CONFIG_I2C=y
CONFIG_I2C_TARGET=y
#CONFIG_NEWLIB_LIBC=y
CONFIG_SENSOR=y
CONFIG_BMP388=y
#CONFIG_GNSS=y
#CONFIG_GNSS_SATELLITES=y

#CONFIG_LOG=y
#CONFIG_LOG_BUFFER_SIZE=8192
#CONFIG_GNSS_DUMP_TO_LOG=y
#CONFIG_GNSS_DUMP_TO_LOG_BUF_SIZE=1024
#CONFIG_GNSS_LOG_LEVEL_DBG=y
#CONFIG_MODEM_MODULES_LOG_LEVEL_DBG=y

#CONFIG_DISK_ACCESS=y
#CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_LOG=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SPI=y
CONFIG_DISK_DRIVERS=y
CONFIG_DISK_DRIVER_MMC=y
